### ISSUE TITLE
Struct inheritance and struct updaters

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/struct-update#1]
See also https://github.com/jackfirth/lens/issues/290

Currently there is no way to generate updaters that update fields of super-structs while preserving the fields of sub-structs.
```
#lang racket

(require struct-update)

(struct foo (a) #:transparent)
(struct bar foo (b) #:transparent)
(define-struct-updaters foo)
(define-struct-updaters bar)

(define x (bar 1 20))
(foo-a-set x 42)
; (foo 42) instead of (bar 42 20)
(bar-foo-a-set x 43)
; bar-foo-a-set: unbound identifier in module in: bar-foo-a-set
```
The `foo-a-set` function sees `x` as a `foo` instead of a `bar`, and returns a `foo`. And there's no alternative function like a `bar-foo-a-set` that could return a  `bar` with the `foo-a` field updated.

**Comment by lexi-lambda** [comment]
As I mentioned on the lens issue, this stuff is hard to do with Racket’s current struct model, and I am not super interested in doing a ton of additional work to support it, given that I would rather just not use struct inheritance. Inheritance is problematic for lots of reasons, so unless you have an idea for a good, clean solution, I’m probably not going to be interested in trying to address it.

If you want to submit a PR that would generate `bar-foo-a-set`-style functions, too, I’d be open to that, but I’m not likely to implement it myself right now.

**Comment by AlexKnauth** [comment]
I just made a pull request for one possible way of approaching this: #3
